# server:
#   servlet: 
#     context-path: /apis/auth/latest
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:172.17.0.4}/auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
